
function(define_build_unit unit_name)
  set_property(GLOBAL PROPERTY ${unit_name}_ROOT ${CMAKE_CURRENT_SOURCE_DIR})
endfunction()

function(unit_add_sources unit_name)
  get_property(unit_root GLOBAL PROPERTY ${unit_name}_ROOT)
  file(RELATIVE_PATH _relPath ${unit_root} "${CMAKE_CURRENT_SOURCE_DIR}")
  foreach(_src ${ARGN})
    if(_relPath)
      list(APPEND unit_srcs "${_relPath}/${_src}")
    else()
      list(APPEND unit_srcs "${_src}")
    endif()
  endforeach()
  set_property(GLOBAL APPEND PROPERTY ${unit_name}_SRCS ${unit_srcs})
endfunction()

function(unit_add_link_deps unit_name)
  foreach(_dep ${ARGN})
    list(APPEND unit_deps "${_dep}")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY ${unit_name}_DEPS ${unit_deps})
endfunction()

function(unit_add_include_dirs unit_name)
  foreach(_inc ${ARGN})
    list(APPEND unit_inc_dirs "${_inc}")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY ${unit_name}_INC_DIRS ${unit_inc_dirs})
endfunction()

