
macro(define_build_unit unit_name unit_root)
  set_property(GLOBAL PROPERTY ${unit_name}_ROOT ${unit_root})
endmacro()

macro(unit_add_sources unit_name)
  get_property(unit_root GLOBAL PROPERTY ${unit_name}_ROOT)
  file(RELATIVE_PATH _relPath ${unit_root} "${CMAKE_CURRENT_SOURCE_DIR}")
  foreach(_src ${ARGN})
    if(_relPath)
      list(APPEND ${unit_name}_SRCS "${_relPath}/${_src}")
    else()
      list(APPEND ${unit_name}_SRCS "${_src}")
    endif()
  endforeach()
  if(_relPath)
    set_property(GLOBAL APPEND PROPERTY ${unit_name}_SRCS ${${unit_name}_SRCS})
  endif()
endmacro()

macro(unit_add_link_deps unit_name)
  foreach(_dep ${ARGN})
    list(APPEND ${unit_name}_DEPS "${_dep}")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY ${unit_name}_DEPS ${${unit_name}_DEPS})
endmacro()

macro(unit_add_include_dirs unit_name)
  foreach(_inc ${ARGN})
    list(APPEND ${unit_name}_INC_DIRS "${_inc}")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY ${unit_name}_INC_DIRS ${${unit_name}_INC_DIRS})
endmacro()

